version: '4'
   
services:  
  airline-coverage-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: airline-coverage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
